(venv) PS C:\Users\Lenovo\UIT\Nam2\SkinSage> python run_app.py
Beauty Analytics - Starting...
Error: Class '<class 'database.User'>' already has a primary mapper defined. 
(venv) PS C:\Users\Lenovo\UIT\Nam2\SkinSage> python -c "
>> import psycopg2
>> from urllib.parse import urlparse
>> import os
>> 
>> try:
>>     from dotenv import load_dotenv
>>     load_dotenv()
>> except: pass
>> 
>> db_url = os.environ.get('DATABASE_URL')
>> parsed = urlparse(db_url)
>> 
>> conn = psycopg2.connect(
>>     host=parsed.hostname,
>>     port=parsed.port,
>>     database=parsed.path[1:],
>>     user=parsed.username,
>>     password=parsed.password
>> )
>>
>> print('Database connection successful!')
>> conn.close()
>> "
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "db.icvqowxrxnqgcceoxxob.supabase.co" to address: No such host is known.

(venv) PS C:\Users\Lenovo\UIT\Nam2\SkinSage> python .\simple_run.py       
Beauty Analytics - Clean Start
Step 1: Creating database tables...
Database creation failed:
Traceback (most recent call last):
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\temp_init.py", line 20, in <module>
    class User(db.Model):
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 100, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 120, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\instrumentation.py", line 684, in register_class
    manager._update_state(
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "C:\Users\Lenovo\UIT\Nam2\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class '__main__.User'>' already has a primary mapper defined.

(venv) PS C:\Users\Lenovo\UIT\Nam2\SkinSage> 